### ISSUE TITLE
편지 하프레이어 QA수정, 메인 배경의 우표패턴 높이 조정

### ISSUE THREAD

**Issue by yujeongJeon** [Nexters/covid-letter-web#154]
### 이슈 상세

-   [x] [QA 이슈](https://www.notion.so/nexters19th/b0ad940f81c44cd5b518d7e4f1df74c1?v=888f245a685a46b6af217d4b47b7d7fc&p=d67a89b20a9a4ad9be5e9ae24bb55e26)
-   [x] 우표 패턴 개수를 `document.body.clientHeight`으로 계산하지 말고 `window.innerHeight`으로 계산

**Comment by siyeons** [comment]
QA 라벨 좋네요~~~ 😀
