### ISSUE TITLE
편지 작성 완료 화면

### ISSUE THREAD

**Issue by siyeons** [Nexters/covid-letter-web#64]
### 이슈 상세

편지 작성 완료 화면 구현하기!! 
로딩 애니메이션 <- 어떻게 하지 😃

**Comment by yujeongJeon** [comment]
> 로딩 애니메이션 <- 어떻게 하지 😃

로딩 애니메이션은 디자이너 분들이 로티로 작성해주셔야 할거 같아요 :)!
